app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//API validation routes no login required
Route::get('/validate_site_json', 'OapiController@validate_site_json');
Route::get('/validate_update_json', 'OapiController@validate_update_json');
Route::get('/plugins_json', 'OapiController@plugins_json');
Route::get('/update_button_json', 'OapiController@update_button_json');


//Dashboard routes
Route::get("/my_subscriptions","DashboardController@my_subscriptions");
Route::post("/create_api_key","DashboardController@create_api_key");
Route::get('/logout', 'DashboardController@logout');
Route::post("/set_lang","DashboardController@set_lang");

//Admin routes
Route::get('/open_tickets', 'AdminController@open_tickets');
Route::get('/customers', 'AdminController@customers');
Route::get('/get_customer/{id}', 'AdminController@get_customer');
Route::get('/test_email', 'AdminController@test_email');

//Otickets routes
Route::resource("otickets","OticketController");
Route::post("store_answer","OticketController@store_answer");
Route::post("update_status","OticketController@update_status");
Route::get("all_tickets","OticketController@all");

//Options routes
Route::resource("wp_global_options","WpGlobalOptionController");

Route::resource("pete_plugins","PetePluginController"); // Add this line in routes.php
Route::resource("oupdates","OupdateController");


Route::get('/', array('as' => 'dashboard.my_subscriptions', 'uses' => 'DashboardController@my_subscriptions'));

app/PetePlugin.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PetePlugin extends Model
{
    //
}

app/Http/Controllers/PetePluginController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\PetePlugin;
use App\DashboardOption;
use Illuminate\Http\Request;
use View;
use Log;

class PetePluginController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct(Request $request){

		$this->middleware('auth.wp');		
		$dashboard_option = new DashboardOption();	
		View::share(compact('dashboard_option'));
	}
	
	
	
	public function index()
	{
		$pete_plugins = PetePlugin::orderBy('id', 'desc')->paginate(10);
		$viewsw = "plugins";
		return view('pete_plugins.index', compact('pete_plugins','viewsw'));
	}
	

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{	
		$viewsw = "plugins";
		return view('pete_plugins.create',compact('viewsw '));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$pete_plugin = new PetePlugin();

		$pete_plugin->title = $request->input("title");
		$pete_plugin->version = $request->input("version");
       
        $pete_plugin->description = $request->input("description");
        $pete_plugin->install_script = $request->input("install_script");
		$pete_plugin->uninstall_script = $request->input("uninstall_script");
		$pete_plugin->update_script = $request->input("uninstall_script");
		
		
		
		if($request->file('image')!= ""){
			Log::info('Entro en logica archivo');
				
			$file = $request->file('image');
	        // SET UPLOAD PATH
	        $destinationPath = 'pete_plugins';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$pete_plugin->image = $fileName;
			
		}

		$pete_plugin->save();

		return redirect()->route('pete_plugins.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$pete_plugin = PetePlugin::findOrFail($id);
		$viewsw = "plugins";
		return view('pete_plugins.show', compact('pete_plugin','viewsw'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$pete_plugin = PetePlugin::findOrFail($id);
		$viewsw = "plugins";
		return view('pete_plugins.edit', compact('pete_plugin','viewsw'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$pete_plugin = PetePlugin::findOrFail($id);

		$pete_plugin->title = $request->input("title");
		$pete_plugin->version = $request->input("version");
        $pete_plugin->description = $request->input("description");
        $pete_plugin->install_script = $request->input("install_script");
		$pete_plugin->uninstall_script = $request->input("uninstall_script");
		$pete_plugin->update_script = $request->input("uninstall_script");
		
		if($request->file('image')!= ""){
			Log::info('Entro en logica archivo');
			Log::info($request->file('image'));
			$file = $request->file('image');
	        // SET UPLOAD PATH
	        $destinationPath = 'plugins_images';
	         // GET THE FILE EXTENSION
	        $extension = $file->getClientOriginalExtension();
	         // RENAME THE UPLOAD WITH RANDOM NUMBER
	        $fileName = rand(11111, 99999) . '.' . $extension;
	         // MOVE THE UPLOADED FILES TO THE DESTINATION DIRECTORY
	        $upload_success = $file->move($destinationPath, $fileName);
			$pete_plugin->image = $fileName;
			
		}

		$pete_plugin->save();

		return redirect()->route('pete_plugins.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$pete_plugin = PetePlugin::findOrFail($id);
		$pete_plugin->delete();

		return redirect()->route('pete_plugins.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/pete_plugins/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3> Plugins / Create </h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('pete_plugins.store') }}" method="POST"  enctype="multipart/form-data">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

				
      		  		<label for="meta_value-field">Title</label>
                    <input type="text" id="title" name="title" class="form-control" value=""/>
					
	  		  		<label for="meta_value-field">Version</label>
	                <input type="text" id="version" name="version" class="form-control" value=""/>
					      
                    <label for="meta_value-field">Description</label>
                    <textarea class="form-control" id="description" rows="3" name="description"></textarea>
					
	                <label for="meta_value-field">Install Script</label>
	                <textarea class="form-control" id="install_script" rows="3" name="install_script"></textarea>
				
	                <label for="meta_value-field">Uninstall Script</label>
	                <textarea class="form-control" id="uninstall_script" rows="3" name="uninstall_script"></textarea>
				
	                <label for="meta_value-field">Update Script</label>
	                <textarea class="form-control" id="update_script" rows="3" name="update_script"></textarea>
                 	
		            <div class="form-group">
		              <label for="zip_file_url-field">Image</label>
	                  <input type="file" id="image" name="image">
		            </div>
				
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('pete_plugins.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/pete_plugins/edit.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h3>PetePlugins / Edit #{{$pete_plugin->id}}</h3>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('pete_plugins.update', $pete_plugin->id) }}" method="POST" enctype="multipart/form-data">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

  		  		<label for="meta_value-field">Title</label>
                <input type="text" id="title" name="title" class="form-control" value="{{$pete_plugin->title}}"/>
				
  		  		<label for="meta_value-field">Version</label>
                <input type="text" id="version" name="version" class="form-control" value="{{$pete_plugin->version}}"/>
				      
                <label for="meta_value-field">Description</label>
                <textarea class="form-control" id="description" rows="7" name="description">{{$pete_plugin->description}}</textarea>
				
				<h3>MAC</h3>
				
                <label for="meta_value-field">Install Script</label>
                <textarea class="form-control" id="install_script" rows="7" name="install_script">{{$pete_plugin->mac_install_script}}</textarea>
				
                <label for="meta_value-field">Uninstall Script</label>
                <textarea class="form-control" id="uninstall_script" rows="7" name="uninstall_script">{{$pete_plugin->mac_uninstall_script}}</textarea>
				
                <label for="meta_value-field">Update Script</label>
                <textarea class="form-control" id="update_script" rows="7" name="update_script">{{$pete_plugin->mac_update_script}}</textarea>
				
				
				<h3>OLINUX</h3>
				
                <label for="meta_value-field">Install Script</label>
                <textarea class="form-control" id="install_script" rows="7" name="install_script">{{$pete_plugin->olinux_install_script}}</textarea>
				
                <label for="meta_value-field">Uninstall Script</label>
                <textarea class="form-control" id="uninstall_script" rows="7" name="uninstall_script">{{$pete_plugin->olinux_uninstall_script}}</textarea>
				
                <label for="meta_value-field">Update Script</label>
                <textarea class="form-control" id="update_script" rows="7" name="update_script">{{$pete_plugin->olinux_update_script}}</textarea>
             	
	            <div class="form-group">
	              <label for="zip_file_url-field">Image</label>
                  <input type="file" id="image" name="image">
	            </div>
				
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('pete_plugins.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/pete_plugins/index.blade.php
@extends('layout')

@section('header')

<style>
	code{
		font-size: 10px !important;
	}
</style>
   
@endsection

@section('content')

   <div class="page-header clearfix">
       <h3>
           PetePlugins
           <a class="btn btn-success pull-right" href="{{ route('pete_plugins.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
       </h3>

   </div>

    <div class="row">
        <div class="col-md-12">
            @if($pete_plugins->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            <th>Version</th>
                            <th>Title</th>
							<th>Image</th>
							<th>Description</th>
							<th>Script</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($pete_plugins as $pete_plugin)
                            <tr>
                                <td>{{$pete_plugin->version}}</td>
								
								<td>{{$pete_plugin->title}}</td>
								<td>
								@if($pete_plugin->image)
									<img class="img-responsive" src="/plugins_images/{{$pete_plugin->image}}">
								@endif
								</td>
								<td>{{$pete_plugin->description}}</td>
								<td>
									<h3>MAC</h3>
									<p>Install script</p>
									<code>{{$pete_plugin->mac_install_script}}</code>
									
									<p>Update script</p>
									<code>{{$pete_plugin->mac_update_script}}</code>
									
									<p>Uninstall script</p>
									<code>{{$pete_plugin->mac_uninstall_script}}</code>
									
									<h3>OLINUX</h3>
									<p>Install script</p>
									<code>{{$pete_plugin->olinux_install_script}}</code>
									
									<p>Update script</p>
									<code>{{$pete_plugin->olinux_update_script}}</code>
									
									<p>Uninstall script</p>
									<code>{{$pete_plugin->olinux_uninstall_script}}</code>
									
									
									<h3>WIN</h3>
									<p>Install script</p>
									<code>{{$pete_plugin->win_install_script}}</code>
									
									<p>Update script</p>
									<code>{{$pete_plugin->win_update_script}}</code>
									
									<p>Uninstall script</p>
									<code>{{$pete_plugin->win_uninstall_script}}</code>
									
								</td>
								
                                
                               <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('pete_plugins.show', $pete_plugin->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('pete_plugins.edit', $pete_plugin->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('pete_plugins.destroy', $pete_plugin->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $pete_plugins->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/pete_plugins/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>PetePlugins / Show #{{$pete_plugin->id}}</h1>
        <form action="{{ route('pete_plugins.destroy', $pete_plugin->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('pete_plugins.edit', $pete_plugin->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                
            </form>

            <a class="btn btn-link" href="{{ route('pete_plugins.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection