app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//API validation routes no login required
Route::get('/validate_site_json', 'OapiController@validate_site_json');
Route::get('/validate_update_json', 'OapiController@validate_update_json');
Route::get('/plugins_json', 'OapiController@plugins_json');
Route::get('/update_button_json', 'OapiController@update_button_json');


//Dashboard routes
Route::get("/my_subscriptions","DashboardController@my_subscriptions");
Route::post("/create_api_key","DashboardController@create_api_key");
Route::get('/logout', 'DashboardController@logout');
Route::post("/set_lang","DashboardController@set_lang");

//Admin routes
Route::get('/open_tickets', 'AdminController@open_tickets');
Route::get('/customers', 'AdminController@customers');
Route::get('/get_customer/{id}', 'AdminController@get_customer');
Route::get('/test_email', 'AdminController@test_email');

//Otickets routes
Route::resource("otickets","OticketController");
Route::post("store_answer","OticketController@store_answer");
Route::post("update_status","OticketController@update_status");
Route::get("all_tickets","OticketController@all");

//Options routes
Route::resource("wp_global_options","WpGlobalOptionController");

Route::resource("pete_plugins","PetePluginController"); // Add this line in routes.php
Route::resource("oupdates","OupdateController");


Route::get('/', array('as' => 'dashboard.my_subscriptions', 'uses' => 'DashboardController@my_subscriptions'));

app/Oupdate.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Oupdate extends Model
{
    //
	protected $table = 'oupdates';

	
}

app/Http/Controllers/OupdateController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\DashboardOption;
use App\Oupdate;
use Illuminate\Http\Request;
use View;
use Log;

class OupdateController extends Controller {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	
	public function __construct(Request $request){

		$this->middleware('auth.wp');		
		$dashboard_option = new DashboardOption();	
		View::share(compact('dashboard_option'));
	}
	
	public function index()
	{
		$oupdates = Oupdate::orderBy('id', 'desc')->paginate(10);

		return view('oupdates.index', compact('oupdates'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('oupdates.create');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param Request $request
	 * @return Response
	 */
	public function store(Request $request)
	{
		$oupdate = new Oupdate();

		$oupdate->parent_version = $request->input("parent_version");
        $oupdate->version = $request->input("version");
        $oupdate->mac_script = $request->input("mac_script");
        $oupdate->olinux_script = $request->input("olinux_script");
        $oupdate->win_script = $request->input("win_script");

		$oupdate->save();

		return redirect()->route('oupdates.index')->with('message', 'Item created successfully.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$oupdate = Oupdate::findOrFail($id);

		return view('oupdates.show', compact('oupdate'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$oupdate = Oupdate::findOrFail($id);

		return view('oupdates.edit', compact('oupdate'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @param Request $request
	 * @return Response
	 */
	public function update(Request $request, $id)
	{
		$oupdate = Oupdate::findOrFail($id);

		$oupdate->parent_version = $request->input("parent_version");
        $oupdate->version = $request->input("version");
        $oupdate->mac_script = $request->input("mac_script");
        $oupdate->olinux_script = $request->input("olinux_script");
        $oupdate->win_script = $request->input("win_script");

		$oupdate->save();

		return redirect()->route('oupdates.index')->with('message', 'Item updated successfully.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$oupdate = Oupdate::findOrFail($id);
		$oupdate->delete();

		return redirect()->route('oupdates.index')->with('message', 'Item deleted successfully.');
	}

}

resources/views/oupdates/_form.blade.php
<label for="meta_value-field">Parent Version</label>
<input type="text" id="parent_version" name="parent_version" class="form-control" value="{{$oupdate->parent_version}}"/>
               
<label for="meta_value-field">Version</label>
<input type="text" id="version" name="version" class="form-control" value="{{$oupdate->version}}"/>
				
<label for="meta_value-field">Mac Script</label>
<textarea class="form-control" id="mac_script" rows="7" name="mac_script">{{$oupdate->mac_script}}</textarea>
				
<label for="meta_value-field">Linux Script</label>
<textarea class="form-control" id="olinux_script" rows="7" name="olinux_script">{{$oupdate->olinux_script}}</textarea>
				
<label for="meta_value-field">Win Script</label>
 <textarea class="form-control" id="win_script" rows="7" name="win_script">{{$oupdate->win_script}}</textarea>

resources/views/oupdates/create.blade.php
@extends('layout')

@section('header')
    <div class="page-header">
        <h1><i class="glyphicon glyphicon-plus"></i> Oupdates / Create </h1>
    </div>
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">

            <form action="{{ route('oupdates.store') }}" method="POST">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

				@include('oupdates._form')
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Create</button>
                    <a class="btn btn-link pull-right" href="{{ route('oupdates.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/oupdates/edit.blade.php
@extends('layout')

@section('header')
    
@endsection

@section('content')
    @include('error')

    <div class="row">
        <div class="col-md-12">
			
		    <div class="page-header">
		        <h3>Oupdates / Edit #{{$oupdate->id}}</h3>
		    </div>

            <form action="{{ route('oupdates.update', $oupdate->id) }}" method="POST">
                <input type="hidden" name="_method" value="PUT">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">

				@include('oupdates._form')
                
                <div class="well well-sm">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a class="btn btn-link pull-right" href="{{ route('oupdates.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                </div>
            </form>

        </div>
    </div>
@endsection

resources/views/oupdates/index.blade.php
@extends('layout')

@section('header')
    
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">
			
		   
				
				<a class="btn btn-success pull-right" href="{{ route('oupdates.create') }}">Create</a>
		        <h3>Oupdates</h3>
		            	
		   
			
            @if($oupdates->count())
                <table class="table table-condensed table-striped">
                    <thead>
                        <tr>
                            
							<th>Parent Version</th>
							<th>Version</th>
                            <th>Scripts</th>
                            <th class="text-right">OPTIONS</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($oupdates as $oupdate)
                            <tr>
                                
								<td>{{$oupdate->parent_version}}</td>
								<td>{{$oupdate->version}}</td>
                                <td>
									{{$oupdate->mac_script}} <br />
									{{$oupdate->olinux_script}}<br />
									{{$oupdate->win_script}}
								</td>
                                <td class="text-right">
                                    <a class="btn btn-xs btn-primary" href="{{ route('oupdates.show', $oupdate->id) }}"><i class="glyphicon glyphicon-eye-open"></i> View</a>
                                    <a class="btn btn-xs btn-warning" href="{{ route('oupdates.edit', $oupdate->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                                    <form action="{{ route('oupdates.destroy', $oupdate->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> Delete</button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
                {!! $oupdates->render() !!}
            @else
                <h3 class="text-center alert alert-info">Empty!</h3>
            @endif

        </div>
    </div>

@endsection

resources/views/oupdates/show.blade.php
@extends('layout')
@section('header')
<div class="page-header">
        <h1>Oupdates / Show #{{$oupdate->id}}</h1>
        <form action="{{ route('oupdates.destroy', $oupdate->id) }}" method="POST" style="display: inline;" onsubmit="if(confirm('Delete? Are you sure?')) { return true } else {return false };">
            <input type="hidden" name="_method" value="DELETE">
            <input type="hidden" name="_token" value="{{ csrf_token() }}">
            <div class="btn-group pull-right" role="group" aria-label="...">
                <a class="btn btn-warning btn-group" role="group" href="{{ route('oupdates.edit', $oupdate->id) }}"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <button type="submit" class="btn btn-danger">Delete <i class="glyphicon glyphicon-trash"></i></button>
            </div>
        </form>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="col-md-12">

            <form action="#">
                <div class="form-group">
                    <label for="nome">ID</label>
                    <p class="form-control-static"></p>
                </div>
                
            </form>

            <a class="btn btn-link" href="{{ route('oupdates.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>

        </div>
    </div>

@endsection